Reading the fraud label for an user from dfp graph
microsoft/Dynamics-365-Fraud-Protection-ManualReview pull request #24
Opened 2021-05-28 21:24 UTC by irinatarn

…and showing it on review page as User Restricted tag, if it is present.
![mr](https://user-images.githubusercontent.com/28061748/120043194-5f64ce00-bfc0-11eb-9c8a-8415493ee63a.png)

2021-05-28 22:59 UTC, satyamamit requested changes

2021-05-28 22:59 UTC, satyamamit commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> +        ItemDTO realItem = modelMapper.map(item, ItemDTO.class);
what is this mapper doing ?

2021-05-28 22:59 UTC, satyamamit commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> +        ExplorerEntity entity = dfpExplorerService.exploreUser(realItem.getPurchase().getUser().getUserId());
I dont see any getPurchase() method on ItemDTO, but do see Purchase it is something automatically done by Java or i am missing something.

2021-05-28 22:59 UTC, satyamamit commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> +                        t.getDestinationNode().equalsIgnoreCase("User") &&
as entity is of Type user in line 64, do we really need this check for source and destination nodes ?

2021-05-28 22:59 UTC, satyamamit commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> +                        t.getData().getAdditionalParams() !=null &&
do we need this check as this will never be null as it is already instantiated in EdgeData class.

![image](https://user-images.githubusercontent.com/544943/120047305-1a916500-bfc9-11eb-88fb-b401e553f715.png)

2021-05-28 22:59 UTC, satyamamit commented on frontend/src/data-services/api-services/models/user-dto.ts
> +    IsFraud: boolean;
why this is part of PurchaseUserDTO but not user as Fraud is user property not PurchaseUser property. If we can keep it as part of user property then we dont need to attach it to each and every purchase but we can just keep it at user level.

2021-05-28 22:59 UTC, satyamamit commented on frontend/src/screens/review-console/item-details/parts/account-summary/account-summary.tsx
> +                value: this.renderValidatedInfo(
how this will work.

![image](https://user-images.githubusercontent.com/544943/120048187-4877a900-bfcb-11eb-96ff-c39cef04fd53.png)

It looks in case user is non fraud we will show Good icon, do we need to show it ?

2021-05-28 22:59 UTC, satyamamit commented on frontend/src/screens/review-console/item-details/item-details.tsx
> +                        <Text className={`${CN}__order-id`}>
may be some other class name?

2021-05-28 23:10 UTC, irinatarn commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> +        ItemDTO realItem = modelMapper.map(item, ItemDTO.class);
Convert the DB object to the item that UX need to consume.

2021-05-28 23:12 UTC, irinatarn commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> +        ExplorerEntity entity = dfpExplorerService.exploreUser(realItem.getPurchase().getUser().getUserId());
Item is a purchase. Item is the enriched thingie in the DB. You don't need to have getPurchase.

2021-05-28 23:17 UTC, irinatarn commented on frontend/src/screens/review-console/item-details/item-details.tsx
> +                        <Text className={`${CN}__order-id`}>
why?

2021-05-28 23:18 UTC, irinatarn commented on frontend/src/data-services/api-services/models/user-dto.ts
> +    IsFraud: boolean;
I don't get what are you trying to say here. Will ping you offline

2021-05-28 23:33 UTC, irinatarn commented on frontend/src/screens/review-console/item-details/item-details.tsx
> +                        <Text className={`${CN}__order-id`}>
Talked offline. Will close the comment

2021-06-01 16:33 UTC, satyamamit commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> -                        t.getData().getAdditionalParams() !=null &&
why did you remove this check as well ?

2021-06-01 16:35 UTC, satyamamit approved these changes

2021-06-01 16:37 UTC, irinatarn commented on backend/queues/src/main/java/com/griddynamics/msd365fp/manualreview/queues/service/PublicItemService.java
> -                        t.getData().getAdditionalParams() !=null &&
Because you pointed out that additionalParams cannot be null - since it is always created as new HashMap(). Remember?

2021-06-01 17:15 UTC, merged