Irinata/bug2
microsoft/Dynamics-365-Fraud-Protection-ManualReview pull request #53
Opened 2021-08-04 20:49 UTC by irinatarn

![image](https://user-images.githubusercontent.com/28061748/128252877-61e6ad7a-8b18-4025-9ca2-0dce42c58e5f.png)

2021-08-05 20:56 UTC, satyamamit requested changes

2021-08-05 20:56 UTC, satyamamit commented on frontend/src/components/items-details-list/items-details-list.tsx
> -            name: 'Order ID',
There are few more files which i see has order ID

![image](https://user-images.githubusercontent.com/544943/128419351-69158efe-64fb-4dfb-b3e6-0982b8dc1fd1.png)

2021-08-05 20:56 UTC, satyamamit commented on frontend/src/screens/review-console/item-details/parts/link-analysis/items-list/items-list.tsx
> +                    : item.purchaseId;
why you have this condistion here. is originalOrderId not coming as customer attributes if yes, then DFP data should also have this.

2021-08-05 20:56 UTC, satyamamit commented on frontend/src/screens/review-console/item-details/parts/link-analysis/items-list/items-list.tsx
> +                    <div className={`${CN}__order-id-cell`}>
is this also showing only on hover ? can you please share screenshot here.

2021-08-06 20:29 UTC, irinatarn commented on frontend/src/screens/review-console/item-details/parts/link-analysis/items-list/items-list.tsx
> +                    : item.purchaseId;
YOu are right

2021-08-06 20:31 UTC, irinatarn commented on frontend/src/screens/review-console/item-details/parts/link-analysis/items-list/items-list.tsx
> +                    <div className={`${CN}__order-id-cell`}>
![copy](https://user-images.githubusercontent.com/28061748/128567924-20641cd9-2840-469b-805a-d03672485b2f.gif)

2021-08-06 20:31 UTC, irinatarn commented on frontend/src/components/items-details-list/items-details-list.tsx
> -            name: 'Order ID',
Corrected.

2021-08-09 21:53 UTC, haixiehx commented
Is it possible to update the PR title to be more informative? in the future it's easier to check the commit histories.

2021-08-09 22:16 UTC, haixiehx commented on frontend/src/screens/review-console/item-details/parts/link-analysis/items-list/items-list.tsx
> +            name: 'Original Order ID',
nit: should "Order" be lower case? "Original order ID", to be consistent with other columns like "Fraud score", "Import date" etc.

2021-08-09 22:20 UTC, haixiehx commented on frontend/src/constants/search.ts
> +    ORIGINAL_ORDER_ID:'ORIGINAL_ORDER_ID'
nit: a space between "ORIGINAL_ORDER_ID:" and " 'ORIGINAL_ORDER_ID'"
eslint might complain if you have it ON.

2021-08-09 22:20 UTC, haixiehx approved these changes

2021-08-09 22:33 UTC, irinatarn commented on frontend/src/screens/review-console/item-details/parts/link-analysis/items-list/items-list.tsx
> +            name: 'Original Order ID',
Fixed.

2021-08-09 22:33 UTC, irinatarn commented on frontend/src/constants/search.ts
> +    ORIGINAL_ORDER_ID:'ORIGINAL_ORDER_ID'
Fixed

2021-08-09 22:45 UTC, haixiehx approved these changes

2021-08-10 18:08 UTC, satyamamit approved these changes

2021-08-10 18:14 UTC, merged